[package]
name = "client"
version = "0.1.0"
authors = ["rogovskyy <bart.rogovsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
